# Generated by Django 5.0 on 2023-12-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=100)),
                ('algorith', models.CharField(choices=[('hashes.SHA256', 'hashes.SHA256'), ('hashes.SHA384', 'hashes.SHA384'), ('hashes.SHA512', 'hashes.SHA512')], max_length=20)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DecryptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=100)),
                ('algorith', models.CharField(choices=[('hashes.SHA256', 'hashes.SHA256'), ('hashes.SHA384', 'hashes.SHA384'), ('hashes.SHA512', 'hashes.SHA512')], max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
