# Generated by Django 5.0 on 2023-12-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptionrequest',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
