# Generated by Django 5.0 on 2023-12-26 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('password', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=20)),
                ('decryption_key', models.BinaryField(blank=True, null=True)),
                ('decrypted_content', models.BinaryField(blank=True, null=True)),
                ('decrypted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
