# Generated by Django 5.0 on 2023-12-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='algorith',
            field=models.CharField(choices=[('SHA256', 'SHA256'), ('SHA3_256', 'SHA3_256'), ('BLAKE2b', 'BLAKE2b')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
