# Generated by Django 5.0 on 2023-12-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_decryptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptionrequest',
            name='uploaded_file',
            field=models.FileField(upload_to='uploaddecry/'),
        ),
    ]
