# Generated by Django 5.0 on 2023-12-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_decryptionrequest_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decryptionrequest',
            old_name='algorithm',
            new_name='algorith',
        ),
    ]
