# Generated by Django 5.0 on 2023-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_algorithm_decryptionrequest_algorith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptionrequest',
            name='decrypted',
        ),
        migrations.RemoveField(
            model_name='decryptionrequest',
            name='decrypted_content',
        ),
        migrations.RemoveField(
            model_name='decryptionrequest',
            name='decryption_key',
        ),
        migrations.AlterField(
            model_name='decryptionrequest',
            name='algorith',
            field=models.CharField(choices=[('hashes.SHA256', 'hashes.SHA256'), ('hashes.SHA384', 'hashes.SHA384'), ('hashes.SHA512', 'hashes.SHA512')], max_length=20),
        ),
    ]
